(function(){
  'use strict';
  const G=window.Jianghu,root=document.getElementById('app'),key='jianghu-life-v2',atlasKey='jianghu-life-atlas',secretAtlasKey='jianghu-life-secret-atlas';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state=null,route='swift',sect='qinglan',origin='poor',result=null,pending=null,storageOkay=true,loadMessage='',unlocked=[],secretUnlocked=[];
  try{
    const saved=localStorage.getItem(key),old=!saved&&localStorage.getItem('jianghu-life-v1');
    if(saved||old){state=G.restore(JSON.parse(saved||old));if(old)loadMessage='已接上青嵐初卷的舊進度。原存檔仍保留，現在可以繼續下山後的人生。';}
    const a=JSON.parse(localStorage.getItem(atlasKey)||'[]');if(Array.isArray(a))unlocked=a.filter(id=>Object.hasOwn(G.endings,id));
    const hidden=JSON.parse(localStorage.getItem(secretAtlasKey)||'[]');if(Array.isArray(hidden))secretUnlocked=hidden.filter(id=>Object.hasOwn(G.endings,id));
  }catch{loadMessage='未能讀取原進度。你可以在「存檔」匯入備份，或建立新人物；原存檔未被刪除。';}
  function remember(){if(state?.phase==='ending'){const id=G.ending(state).id;const collection=state.cheat?secretUnlocked:unlocked;if(!collection.includes(id))collection.push(id);}}
  function save(){remember();try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem(atlasKey,JSON.stringify(unlocked));localStorage.setItem(secretAtlasKey,JSON.stringify(secretUnlocked));storageOkay=true;}catch{storageOkay=false;}status();}
  function status(){document.getElementById('save-status').textContent=state?(storageOkay?'此生已自動保存':'無法自動保存，請匯出存檔'):'從初入江湖，到山河回望。';}
  function effects(e){return `<div class="effect-list">${Object.entries(e||{}).filter(([,v])=>v!==0).map(([k,v])=>`<span class="${v>=0?'positive':'negative'}">${esc(G.labels[k]||k)} ${v>0?'+':''}${v}</span>`).join('')}</div>`;}
  function notice(){return result?`<div class="notice" role="status"><strong>${esc(result.title)}</strong><p>${esc(result.text)}</p>${effects(result.effect)}</div>`:'';}
  function freshSeed(){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);return '江湖-'+bytes[0].toString(36).toUpperCase();}
  function intro(){return `<section class="opening enter"><div><div class="eyebrow">文字武俠 · 人生養成</div><div class="hero-heading"><h1 class="hero-title">一念入江湖<br><em>一生有回響</em></h1><span class="seal">山河故人</span></div><p class="hero-copy">十五歲，你踏進一座陌生的山門。<br>此後半生，練的是武，選的是人生。<br>有人等你登頂，也有人等你回家。</p><div class="intro-points"><span><b>三門</b>不同出身，不同武道</span><span><b>半生</b>從少年到兩鬢霜白</span><span><b>八卷</b>寫下你的江湖小傳</span></div><div class="opening-note">十五章人生 · 修行擲骰 · 隨機江湖際遇<br>建議分段遊玩，隨時離開、接續此生。</div>${loadMessage?`<p class="notice">${esc(loadMessage)}</p>`:''}</div><form id="create-form" class="creation paper"><div class="eyebrow">山門已開，靜候來人</div><h2>此生，從何處開始</h2><div class="creation-row"><div><label for="name">俠客姓名</label><input id="name" name="name" maxlength="12" value="沈行舟" autocomplete="off" required></div><div><label for="seed">命運種子</label><input id="seed" name="seed" maxlength="32" value="${freshSeed()}" autocomplete="off"></div></div><fieldset><legend>出身</legend><div class="selection-grid">${Object.entries(G.origins).map(([id,o])=>`<button type="button" class="selection" data-origin="${id}" aria-pressed="${origin===id}"><strong>${o.name}</strong></button>`).join('')}</div><p class="selection-desc" id="origin-desc">${G.origins[origin].desc}</p></fieldset><fieldset><legend>拜入門派</legend><div class="selection-grid">${Object.entries(G.sects).map(([id,o])=>`<button type="button" class="selection" data-sect="${id}" aria-pressed="${sect===id}"><strong>${o.name}</strong></button>`).join('')}</div><p class="selection-desc" id="sect-desc">${G.sects[sect].desc}</p></fieldset><fieldset><legend>主修武學</legend><div class="selection-grid">${Object.entries(G.routes).map(([id,r])=>`<button type="button" class="selection" data-route="${id}" aria-pressed="${route===id}"><strong>${r.name}</strong></button>`).join('')}</div><p class="selection-desc" id="route-desc">${G.routes[route].desc}</p></fieldset><button class="primary" type="submit">踏入江湖 <span>→</span></button><p class="tiny">同種子、同出身、同選擇，重現同一段人生。<br>本機自動存檔 · 無須登入 · 全程離線可玩</p></form></section>`;}
  function sidebar(){return `<aside class="sidebar paper"><div class="identity"><div class="portrait" aria-hidden="true">${esc(state.name.slice(0,1))}</div><h2 class="character-name">${esc(state.name)}</h2><div class="route-name">${G.sects[state.sect].name} · ${G.origins[state.origin].name}</div><span class="pill">${state.phase==='ending'?65:G.age(state)} 歲 · ${state.year<=5?'門中弟子':G.vocations[state.vocation]}</span></div><div class="vitals"><div class="vital"><small>健康</small><b class="${state.health<35?'negative':''}">${state.health}<small class="denominator"> /100</small></b></div><div class="vital"><small>內力</small><b>${state.energy}<small class="denominator"> /100</small></b></div></div><div class="martial"><strong>${G.routes[state.route].name}</strong><small>${G.mastery(state)}</small></div><div class="stats">${['skill','body','inner','agility','insight'].map(k=>`<div class="stat"><div class="stat-label"><span>${G.labels[k]}</span><span>${state[k]}</span></div><div class="track"><i style="width:${state[k]}%"></i></div></div>`).join('')}</div><div class="social-stats">${['fame','virtue','contribution','legacy'].map(k=>`<div><small>${G.labels[k]}</small><b>${state[k]}</b></div>`).join('')}</div><div class="extra-stats"><span>盤纏 <b>${state.money}</b> 兩</span>${state.flags.business?'<span>商路分紅 +18／章</span>':''}</div><p class="tiny growth-note">${state.version===3?'每人的潛力不同；超過潛力後修行成本提高。': '舊版人生 · 固定行動規則'}</p></aside>`;}
  function relationships(){const next=Object.entries(G.duelInfo).find(([year])=>Number(year)>=state.year),rows=[
    ['沈照雪','授業恩師','master',state.flags.masterBook?'你把她一生的功夫整理成書。':state.flags.head?'她將山門託付給了你。':state.master>=45?'她開始放心把事情交給你。':'她在看你的功夫，也在看你的心。'],
    ['陸長風','同門師兄','brother',state.flags.treated?'你帶他求醫，他終於肯好好養傷。':state.flags.healed?'他記得大比前夜那一掌暖意。':state.flags.helped?'他一直記得山門外那一擔水。':state.brother>=45?'常年的往來，讓你們漸漸熟悉。':'有些話，要慢慢才會說。'],
    ['顧寒',state.flags.reconcile?'半生故人':'同屆勁敵','rival',state.flags.reconcile?'你們終於能不談勝負地喝一壺茶。':state.flags.understood?'你聽過他不敢輸的理由。':state.flags.honor?'你拒絕暗算，他便敬你三分。':state.flags.sparred?'日落後的那場切磋，他沒忘。':'他想知道，你能走多遠。']
  ];return `<aside class="relationships"><h3>人在江湖</h3>${rows.map(([name,title,k,memory])=>`<div class="relationship"><strong>${name}<span class="relation-value">${state[k]}/100</span></strong><small class="muted">${title} · ${G.labels[k]}</small><p>${memory}</p></div>`).join('')}${state.year>=10?`<div class="relationship"><strong>林溪<span class="relation-value">傳承 ${state.legacy}</span></strong><small class="muted">${state.flags.disciple?'門下弟子':'後起之秀'}</small><p>${state.flags.successor?'他帶著你教的功夫，走向了自己的江湖。':state.flags.disciple?'他記得你願意教他的那一天。':'偶然的指點，也可能改變一生。'}</p></div>`:''}${next&&state.phase!=='ending'?`<div class="goal"><span class="eyebrow">前路所向</span><b>${G.chapters[Number(next[0])-1].age} 歲 · ${next[1].name}</b><p>三回合交鋒，兩合得勢即勝。敗戰仍會繼續人生，勝負會留在往後的故事裡。</p></div>`:''}<div class="side-note">「名次只能替你開一扇門，<br>走出去以後，還得看你自己。」<span>— 沈照雪</span></div></aside>`;}
  function journal(){return `<details class="journal"><summary>江湖紀事 · ${state.history.length} 段往事</summary>${state.history.slice().reverse().map(h=>`<div class="journal-entry"><small>${esc(h.age||G.chapters[h.year-1].age)} 歲 · ${G.chapters[h.year-1].title}</small><b>${esc(h.title)}</b><p>${esc(h.text)}</p>${effects(h.effect)}</div>`).join('')}</details>`;}
  function timeline(){return `<details class="timeline"><summary>此生行程 · 第 ${state.year}／15 章 <span>查看前路</span></summary><div class="timeline-grid">${G.chapters.map((c,i)=>`<div class="${i+1===state.year?'current':i+1<state.year?'past':''}"><small>${c.age} 歲</small><strong>${c.title}</strong>${state.duels.find(d=>d.year===i+1)?`<em>${state.duels.find(d=>d.year===i+1).won?'勝出':'落敗'}</em>`:''}</div>`).join('')}</div></details>`;}
  function trainingView(){
    const t=state.training;
    return `<div class="eyebrow">${G.chapters[state.year-1].title} / 修行</div><h2>${t.rolled?'把這段光陰，練進骨血。':'今年，命運會給你什麼？'}</h2><p class="intro">先擲骰，再決定把每一顆成果投入哪項能力。潛力不同，同樣的努力也會走出不同的路。</p>${!t.rolled?`<button class="primary wide" data-roll>擲出修行骰 →</button><p class="tiny">${state.health<35?'傷勢未癒，本章修行骰減少一顆。':'本章可獲得 3～6 顆修行骰。'}骰出後自動保存。</p>`:`<div class="dice-tray" aria-label="修行骰">${t.dice.map((d,i)=>`<span class="fate-die ${i<t.index?'used':i===t.index?'current':''}" aria-label="第 ${i+1} 顆：${d} 點${i<t.index?'，已分配':''}">${d}</span>`).join('')}</div><p class="dice-cue" role="status">${t.index<t.dice.length?`第 ${t.index+1} 顆 · ${t.dice[t.index]} 點，投入哪裡？`:'全部分配完成，確認後走入江湖。'}</p><div class="training-rows">${G.trainingKeys.map(k=>`<button class="training-row" data-allocate="${k}" ${t.index===t.dice.length||state[k]>=100?'disabled':''}><strong>${G.labels[k]}</strong><span>${state[k]} <small>／潛力 ${state.potential[k]}</small></span><small>${state[k]>=100?'已臻圓滿 · ':''}每級 ${G.cost(state,k)} 點 · 蓄力 ${state.carry[k]}／${G.cost(state,k)}</small></button>`).join('')}</div><div class="ending-actions"><button data-undo ${t.index?'':'disabled'}>復原上一顆</button><button class="primary" data-finish-training ${t.index===t.dice.length?'':'disabled'}>確認修行 →</button></div>`}<div class="trait-tags">${Object.keys(state.traits).filter(k=>state.traits[k]).map(k=>`<span>${G.traits[k]}</span>`).join('')}</div>${notice()}`;
  }
  function yearReview(){return `<div class="eyebrow">${G.age(state)} 歲 / 歲月回望</div><h2>這一年，留下了什麼？</h2><ul class="review-list">${state.history.filter(h=>h.year===state.year&&['event','training','battle','trait'].includes(h.type)).map(h=>`<li>${esc(h.title)}<small>${esc(h.text)}</small></li>`).join('')}</ul><button class="primary wide" data-next>走向 ${G.chapters[state.year].age} 歲 →</button><p class="tiny">跨章自動調養、結算旅途收入；志向、商路與弟子會帶來後續回響。</p>`;}
  function duelView(){const d=G.duelInfo[state.year];return `<div class="eyebrow">${d.name} / ${d.opponent}</div><h2>這一次，如何應戰？</h2><p class="intro">選擇一種策略，三合自動結算。能力、健康與每合骰點共同決定勝負。</p><div class="choice-list">${[['safe','穩守根基','策略固定 +7，骰點不影響加成。'],['balanced','見招拆招','策略為骰點 ×2，介於 +2～+12。'],['bold','放手搶攻','策略為骰點 ×4−7，介於 −3～+17。']].map(([id,title,hint])=>`<button class="choice-button" data-duel="${id}"><span><strong>${title}</strong><small>${hint}</small></span><span>→</span></button>`).join('')}</div><p class="tiny">敗戰仍會繼續人生，高骰點不等於必勝。</p>`;}
  function actions(){if(state.version===3)return trainingView();const ch=G.chapters[state.year-1];return `<div class="eyebrow">${state.year<=5?G.sects[state.sect].place:ch.stage} / 安排光陰</div><h2>${ch.title}</h2><p class="intro">${ch.desc}</p><div class="section-line"><span>這段歲月，留給什麼</span><strong>尚餘 ${state.ap} 次行動</strong></div><div class="action-grid">${Object.entries(G.actions).filter(([id])=>id!=='teach'||state.year>=10).map(([id,a])=>`<button class="action-button" data-action="${id}" ${G.canAct(state,id)?'':'disabled'}><span class="action-icon" aria-hidden="true">${a.icon}</span><span><strong>${a.name}</strong><small>${a.desc}${id==='medicine'&&!G.unlimited(state)&&state.money<12?' · 盤纏不足':''}</small></span></button>`).join('')}</div><p class="tiny">${G.sects[state.sect].desc}${state.year>=6?' '+({wander:'行俠志向：歷練額外 +2 聲望。',guardian:'守護志向：拜訪師兄額外 +3 健康。',leader:'掌門志向：差事額外 +3 貢獻。'}[state.vocation]):''}<br>數值為基礎收益，成長遞減與上限後的實得變化會顯示於紀錄。</p>${notice()}`;}
  function eventView(){const e=G.event(state);return `<div class="eyebrow">${esc(e.who)}</div><h2>${esc(e.title)}</h2><p class="event-body">${esc(e.body)}</p><div class="choice-list">${e.choices.map((c,i)=>`<button class="choice-button" data-choice="${i}" ${c.enabled?'':'disabled'}><span class="number">0${i+1}</span><span><strong>${esc(c.label)}</strong>${state.version===3&&c.hint?`<small class="risk-hint">${esc(c.hint)}</small>`:effects(c.preview)}${c.locked?`<small class="negative">${c.locked}</small>`:''}${c.flag?.startsWith('vocation:')?`<small>人生志向：${G.vocations[c.flag.split(':')[1]]}</small>`:''}</span><span class="arrow">↗</span></button>`).join('')}</div><p class="tiny">眼前的得失寫在此處，長遠的回響留給往後的人生。</p>`;}
  function outcome(){return `<div class="eyebrow">${pending.type==='battle'?'交鋒之後':'一念之後 / 往事已留下'}</div><h2>${esc(pending.title)}</h2><p class="event-body">${esc(pending.text)}</p>${effects(pending.effect)}${pending.type==='battle'&&state.battle.round===3?`<div class="notice"><strong>${state.battle.wins>=2?'此戰勝出':'此戰落敗'} · ${state.battle.wins} 勝 ${3-state.battle.wins} 負</strong><p>${G.duelInfo[state.year][state.battle.wins>=2?'win':'lose']}</p></div>`:''}<button class="primary wide" data-continue>${state.phase==='ending'?'回望這一生':state.phase==='battle'?'繼續交鋒':state.phase==='review'?'回看這段歲月':'繼續這段人生'} <span>→</span></button><p class="tiny">${state.phase==='ending'?'故事已走到晚年，新的篇章由後來的人接下。':'進度已保存。每一次抉擇都可以在江湖紀事中回看。'}</p>`;}
  function review(){if(state.version===3)return yearReview();const duel=state.duels.find(d=>d.year===state.year);return `<div class="eyebrow">${G.age(state)} 歲 / 歲月回望</div><h2>${state.year===5?'山門之外，還有江湖。':'歲月向前，往事留下。'}</h2><p class="intro">${duel?`${esc(duel.name)}：${duel.wins} 勝 ${3-duel.wins} 負。${G.duelInfo[state.year][duel.won?'win':'lose']}`:'這段日子做過的選擇，會陪你走進下一程。'}</p><ul class="review-list">${state.history.filter(h=>h.year===state.year&&h.type==='event').map(h=>`<li>${esc(h.title)}<small>${esc(h.text.split('。')[0])}</small></li>`).join('')}</ul><button class="primary wide" data-next>走向 ${G.chapters[state.year].age} 歲 · ${G.chapters[state.year].title} <span>→</span></button><p class="tiny">人生以重要階段推進，略過平淡的日子。<br>下章內力 +12；${G.chapters[state.year].age>=50?`健康 ${state.flags.longevity?'−2':'−6'}`:'健康 +4'}${state.flags.business?'；商路分紅 +18 兩':''}。</p>`;}
  function battle(){if(state.version===3)return duelView();const st=G.stance(state),d=G.duelInfo[state.year];return `<div class="eyebrow">${d.name} / 第 ${state.battle.round+1} 合，共三合</div><h2>${state.year===15?'把這一生，交給下一代。':'看清這一合，再出手。'}</h2><div class="battle-vs"><div><strong>${esc(state.name)}</strong><small>${G.routes[state.route].name} · ${G.mastery(state)}</small></div><em>對</em><div><strong>${d.opponent}</strong><small>${d.style}</small></div></div><p class="opponent-stance"><span>對手意圖 · ${st.name}</span>${st.hint}</p><div class="section-line"><span>判斷局勢，選擇出招</span><span class="score">${state.battle.wins} 合得勢</span></div><div class="battle-moves">${Object.entries(G.moves).map(([id,n])=>`<button data-fight="${id}" ${id==='special'&&!G.freeSpecial(state)&&state.energy<18?'disabled':''}>${n}<small>${id==='attack'?'克制試探 · 快劍加成':id==='guard'?'克制搶攻 · 重劍加成':id==='probe'?'克制守勢 · 悟性／掌法加成':`${G.routes[state.route].special} · ${G.freeSpecial(state)?'不耗內力':'消耗 18 內力'}`}</small></button>`).join('')}</div><p class="tiny">三合贏兩合即勝。低健康影響出招，命運加成 1～6 點。<br>勝負由實力、策略、狀態與命運共同決定；落敗也能繼續人生。</p>`;}
  function endingView(){const e=G.ending(state);return `<span class="ending-stamp">${e.tag} · 此生已成卷</span><div class="eyebrow">六十五歲 / 山河故人</div><h2 class="ending-title">${e.title.replace('，','，<br>')}</h2><p class="event-body">${e.body}</p><div class="life-summary">${esc(state.name)}，出身${G.origins[state.origin].name}，十五歲拜入${G.sects[state.sect].name}，修${G.routes[state.route].name}。<br>一生志向：${G.vocations[state.vocation]} · 武學境界：${G.mastery(state)}<br>${state.flags.helped?'你曾替師兄挑起一擔水。':''}${state.flags.rescue?(state.version===3?'你曾為白蘆渡登台守擂。':'你曾在山洪中救下一個人。'):''}${state.flags.disciple?'你曾為一個提木劍的孩子打開山門。':''}${state.flags.atoned?'你也曾回頭補還自己的虧欠。':''}<br>聲望 ${state.fame} · 俠義 ${state.virtue} · 傳承 ${state.legacy}</div><div class="duel-history">${state.duels.map(d=>`<div><span>${G.chapters[d.year-1].age} 歲 · ${esc(d.name)}</span><b>${d.won?'勝':'負'} · ${d.wins}：${3-d.wins}</b></div>`).join('')}</div><div class="ending-actions"><button class="primary" id="download">保存江湖小傳 ↓</button><button data-atlas>人生圖鑑 ${unlocked.length}／8</button><button data-restart>另起一段人生</button></div><p class="tiny">結局由你的餘生選擇與累積共同決定。<br>同一片江湖，還有不同的人生。你的已解鎖圖鑑會保留。</p>`;}
  function render(){
    status();document.getElementById('restart').hidden=!state;if(!state){root.innerHTML=intro();bind();return;}
    remember();const ch=G.chapters[state.year-1],content=pending?outcome:{action:actions,event:eventView,review,battle,ending:endingView}[state.phase];
    root.innerHTML=`${state.version!==3?'<div class="upgrade-note">這是保留原規則的舊版人生。新版骰子玩法請先備份存檔，再重啟人生。</div>':''}${state.cheat&&!G.cheatInfo[state.cheat].hidden?`<div class="upgrade-note">${G.cheatInfo[state.cheat].text}</div>`:''}${loadMessage?`<div class="upgrade-note" role="status">${esc(loadMessage)}</div>`:''}<div class="shell">${sidebar()}<section class="main-column"><div class="year-strip"><span class="year-mark">${state.phase==='ending'?65:G.age(state)} 歲 <small class="muted">/ ${ch.stage}</small></span><span class="chapter-counter">第 ${state.year} / 15 章</span></div><div class="life-progress" aria-label="人生進度 ${state.year}/15">${G.chapters.map((_,i)=>`<i class="${i<state.year?'active':''}"></i>`).join('')}</div><div class="chapter-panel paper enter" id="chapter" tabindex="-1">${content()}</div>${timeline()}${journal()}</section>${relationships()}</div>`;bind();
  }
  function focusChapter(){const el=document.getElementById('chapter');el?.focus({preventScroll:true});if(window.innerWidth<700)el?.scrollIntoView({behavior:'auto',block:'start'});}
  function update(fn,showOutcome=false){try{state=fn();result=state.history.at(-1);pending=showOutcome?state.history.slice().reverse().find(h=>h.type==='event'||h.type==='battle'):null;loadMessage='';save();render();focusChapter();}catch(err){loadMessage=err.message;render();}}
  function askRestart(){document.getElementById('restart-dialog').showModal();}
  function downloadFile(name,text,type){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const utility=document.getElementById('utility-dialog'),utilityContent=document.getElementById('utility-content');
  function showUtility(html){utilityContent.innerHTML=html;utility.showModal();}
  function biographyPreview(){
    const e=G.ending(state);
    const text=`江湖一生 · ${state.name}\n${e.title}\n${e.body}\n出身：${G.origins[state.origin].name}｜門派：${G.sects[state.sect].name}\n命運種子：${state.seed}\n${state.cheat&&!G.cheatInfo[state.cheat].hidden?'祕笈人生（不計入正常圖鑑）\n':''}武學：${G.routes[state.route].name}\n\n`+state.history.map(h=>`${h.age||G.chapters[h.year-1].age}歲｜${h.title}\n${h.text}`).join('\n\n');
    showUtility(`<div class="eyebrow">山河故人 / 此生已成卷</div><h2 id="utility-title">你的江湖小傳</h2><p class="export-hint">完整保存這一生的選擇與往事。可以下載文字檔，也可以選取全文後複製到自己的筆記。</p><label class="save-label" for="biography-text">人生小傳全文</label><textarea id="biography-text" readonly spellcheck="false">${esc(text)}</textarea><div class="ending-actions"><button class="primary" id="download-biography">下載小傳 TXT</button><button id="select-biography">選取全文</button></div><p class="tiny" id="biography-feedback" role="status">若瀏覽器未開始下載，仍可選取全文複製保存。</p>`);
    document.getElementById('download-biography').onclick=()=>{downloadFile('江湖一生_人生小傳.txt',text,'text/plain;charset=utf-8');document.getElementById('biography-feedback').textContent='已要求瀏覽器下載；若沒有出現檔案，可用「選取全文」複製保存。';};
    document.getElementById('select-biography').onclick=()=>{const field=document.getElementById('biography-text');field.focus();field.select();document.getElementById('biography-feedback').textContent='全文已選取，可按 Ctrl+C 複製（Mac 使用 ⌘C）。';};
  }
  function atlas(){showUtility(`<div class="eyebrow">每一種人生，都值得留下</div><h2 id="utility-title">人生圖鑑 <small>${unlocked.length}／8</small></h2><div class="atlas-grid">${Object.entries(G.endings).map(([id,e])=>`<article class="atlas-card ${unlocked.includes(id)?'unlocked':''}"><span>${unlocked.includes(id)?'已留下此卷':'尚未經歷'}</span><h3>${e.tag}</h3><p>${unlocked.includes(id)?e.title:e.hint}</p></article>`).join('')}</div><p class="tiny">${secretUnlocked.length?`別卷人生已記錄 ${secretUnlocked.length} 種結局，與正常圖鑑分開保存。<br>`:''}圖鑑只記錄本瀏覽器經歷過的結局。匯出的存檔也會攜帶已解鎖篇章。</p>`);}
  function guide(){showUtility(`<div class="eyebrow">江湖入門 · 骰子人生</div><h2 id="utility-title">少一點安排，多一點命運</h2><div class="guide-copy"><p><b>每章先擲修行骰。</b>正常取得 3～6 顆；健康低於 35 時少一顆，至少兩顆。依序把骰點分配給五項能力，確認前可以復原，不能重骰。</p><p><b>資質各有長短。</b>潛力是成長開始變慢的位置，不是硬上限。能力達 60／85 後每級成本增加，超過潛力再乘三；不足升級的點數保留在蓄力槽。</p><p><b>每章兩件事。</b>先遇一張依年齡與狀態抽出的江湖事件，再作一個人生決定。事件三種應對都有明確成功率及代價；人情與志向由你自己選擇。</p><p><b>過往會改變命運。</b>四次穩中求進成功可解鎖厚積薄發；三次全力一搏成功可解鎖逆境逢生；十二顆骰投入同一能力可解鎖專精一道。</p><p><b>比武只選一次策略。</b>穩守固定加成、應變隨骰點增益、搶攻波動最大，三合自動結算。實力不足時，高骰點也未必能贏。</p><p><b>自動存檔。</b>換裝置前可匯出 JSON。舊人物維持原版玩法；新建人物使用骰子規則。舊版的歷史、圖鑑與存檔仍可使用。</p></div>`);}
  function saveMenu(){
    const exported=state?JSON.stringify({game:'jianghu-life',state,unlocked,secretUnlocked},null,2):'';
    showUtility(`<div class="eyebrow">把此生，隨身帶走</div><h2 id="utility-title">存檔與接續</h2><p class="intro">${state?`${esc(state.name)} · ${G.age(state)} 歲 · ${G.chapters[state.year-1].title}`:'目前尚未建立人物。可匯入 JSON 存檔接續。'}</p>${state?'<button id="export-save" class="primary wide">下載目前存檔 JSON</button>':''}<label class="save-label" for="save-text">存檔內容（可複製備份，或貼上要載入的內容）</label><textarea id="save-text" rows="7" spellcheck="false">${esc(exported)}</textarea><label class="save-label" for="save-file">或選擇存檔檔案</label><input type="file" id="save-file" accept=".json,application/json"><p class="tiny">載入會替換目前人生；若想保留，請先下載目前存檔。若下載受限，可複製上方完整文字另存為 .json。損壞的存檔不會覆蓋進度。</p><button id="import-save" class="wide">載入並接續這份人生</button><p id="save-feedback" role="status" class="tiny"></p>`);
    document.getElementById('export-save')?.addEventListener('click',()=>downloadFile('江湖一生_存檔.json',exported,'application/json;charset=utf-8'));
    document.getElementById('save-file').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;if(file.size>1000000){document.getElementById('save-feedback').textContent='存檔超過大小限制。';return;}try{document.getElementById('save-text').value=await file.text();}catch{document.getElementById('save-feedback').textContent='無法讀取檔案。';}};
    document.getElementById('import-save').onclick=()=>{try{const raw=document.getElementById('save-text').value;if(raw.length>1000000)throw Error('存檔超過大小限制');const data=JSON.parse(raw.replace(/^\uFEFF/,''));const next=G.restore(data.state||data);const incoming=Array.isArray(data.unlocked)?data.unlocked.filter(id=>Object.hasOwn(G.endings,id)):[];const incomingSecret=Array.isArray(data.secretUnlocked)?data.secretUnlocked.filter(id=>Object.hasOwn(G.endings,id)):[];secretUnlocked=[...new Set([...secretUnlocked,...incomingSecret])];state=next;unlocked=[...new Set([...unlocked,...incoming])];pending=null;result=null;loadMessage='存檔已載入，繼續這段人生。';save();utility.close();render();focusChapter();}catch(err){document.getElementById('save-feedback').textContent=`未載入：${err.message}`;}};
  }
  function bind(){
    for(const kind of ['route','sect','origin'])root.querySelectorAll(`[data-${kind}]`).forEach(b=>b.onclick=()=>{const id=b.dataset[kind];if(kind==='route')route=id;else if(kind==='sect')sect=id;else origin=id;root.querySelectorAll(`[data-${kind}]`).forEach(x=>x.setAttribute('aria-pressed',String(x.dataset[kind]===id)));document.getElementById(`${kind}-desc`).textContent=({route:G.routes,sect:G.sects,origin:G.origins}[kind])[id].desc;});
    const form=document.getElementById('create-form');if(form)form.onsubmit=e=>{e.preventDefault();state=G.create(form.elements.name.value,route,form.elements.seed.value,{sect,origin});result=state.cheat?state.history[0]:null;pending=null;loadMessage='';save();render();window.scrollTo(0,0);};
    root.querySelector('[data-roll]')?.addEventListener('click',()=>update(()=>G.rollTraining(state)));
    root.querySelectorAll('[data-allocate]').forEach(b=>b.onclick=()=>update(()=>G.allocate(state,b.dataset.allocate)));
    root.querySelector('[data-undo]')?.addEventListener('click',()=>update(()=>G.undoAllocation(state)));
    root.querySelector('[data-finish-training]')?.addEventListener('click',()=>update(()=>G.finishTraining(state)));
    root.querySelectorAll('[data-duel]').forEach(b=>b.onclick=()=>update(()=>G.resolveDuel(state,b.dataset.duel),true));
    root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>update(()=>G.act(state,b.dataset.action)));
    root.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>update(()=>G.choose(state,Number(b.dataset.choice)),true));
    root.querySelectorAll('[data-fight]').forEach(b=>b.onclick=()=>update(()=>G.fight(state,b.dataset.fight),true));
    root.querySelector('[data-continue]')?.addEventListener('click',()=>{pending=null;result=null;render();focusChapter();});
    root.querySelector('[data-next]')?.addEventListener('click',()=>update(()=>G.nextYear(state)));
    root.querySelectorAll('[data-restart]').forEach(b=>b.onclick=askRestart);root.querySelectorAll('[data-atlas]').forEach(b=>b.onclick=atlas);
    document.getElementById('download')?.addEventListener('click',biographyPreview);
  }
  document.getElementById('restart').onclick=askRestart;document.getElementById('brand').onclick=e=>{e.preventDefault();if(state)askRestart();};
  document.getElementById('cancel-restart').onclick=()=>document.getElementById('restart-dialog').close();
  document.getElementById('confirm-restart').onclick=()=>{state=null;result=null;pending=null;loadMessage='';try{localStorage.removeItem(key);localStorage.removeItem('jianghu-life-v1');}catch{}document.getElementById('restart-dialog').close();render();window.scrollTo(0,0);};
  document.getElementById('guide-button').onclick=guide;document.getElementById('atlas-button').onclick=atlas;document.getElementById('save-button').onclick=saveMenu;document.getElementById('close-utility').onclick=()=>utility.close();
  remember();render();
})();
