const test=require('node:test'),assert=require('node:assert/strict');
const G=require('../core'),R=require('../records');
function ended(){let s=R.begin(G.create('問天','palm','Marrash',{sect:'tingyu',origin:'merchant'}),G,'test-life');for(let guard=0;guard<400&&s.phase!=='ending';guard++){
 if(s.phase==='action'){if(!s.training.rolled)s=G.rollTraining(s);else if(s.training.index<s.training.dice.length)s=G.allocate(s,G.trainingKeys.reduce((a,b)=>s[a]<s[b]?a:b));else s=R.observe(G.finishTraining(s),G);}
 else if(s.phase==='event')s=R.observe(G.choose(s,0),G);else if(s.phase==='battle')s=R.observe(G.resolveDuel(s,'bold'),G);else if(s.phase==='crossroads')s=R.observe(G.chooseCrossroads(s,G.crossroads(s).choices[0].enabled?0:2),G);else s=R.observe(G.nextYear(s),G);
 }return s;}
test('快照只記錄已確認能力；不改變種子進度',()=>{const base=G.create('甲','swift','Marrash');let s=R.begin(base,G,'first');assert.equal(s.rng,base.rng);s=G.allocate(G.rollTraining(s),'skill');const observed=R.observe(s,G);assert.equal(observed.chronicle.peaks.skill,base.skill);assert.equal(R.report(observed,G).stats.find(x=>x.key==='skill').final,base.skill);});
test('完整人生報告包含實際戰績、渡劫、成長、人物及全部原文',()=>{const s=ended(),r=R.report(s,G);assert.equal(s.phase,'ending');assert.equal(r.identity.age,200);assert.equal(r.summary.duelsWon+r.summary.duelsLost,5);assert.equal(r.summary.trialsWon,7);assert.equal(r.summary.trialsLost,0);assert.ok(r.summary.diceCount>40);assert.ok(r.coverage.complete);assert.equal(r.growth.length,22);assert.ok(r.stats.every(x=>x.peak>=x.final));assert.ok(r.honors.some(x=>x.title==='九霄登仙'));assert.equal(r.years.flatMap(x=>x.records).length,s.history.length);assert.ok(R.text(r).includes(s.history[0].text));});
test('舊存檔不編造初始能力與歷史巔峰',()=>{const s=ended();delete s.chronicle;const r=R.report(s,G);assert.equal(r.coverage.complete,false);assert.equal(r.growth.length,0);assert.ok(r.stats.every(x=>x.initial===null&&x.peak===null));assert.ok(r.coverage.note.includes('未留存'));});
test('藏卷刷新去重，新開同種子的人生獨立保存',()=>{const s=ended();let a=R.add([],s,G,'2026-09-22T00:00:00Z');a=R.add(a,s,G,'2026-09-23T00:00:00Z');assert.equal(a.length,1);const next=structuredClone(s);next.chronicle.id='another-life';a=R.add(a,next,G);assert.equal(a.length,2);assert.equal(a[0].state.seed,s.seed);});
test('備份整包驗證，壞資料不破壞已有藏卷',()=>{const a=R.add([],ended(),G),pack=R.pack(a);assert.deepEqual(R.merge([],pack,G),a);assert.deepEqual(R.merge(a,pack,G),a);const bad=structuredClone(pack);bad.entries[0].state.year=999;assert.throws(()=>R.merge(a,bad,G));assert.equal(a.length,1);const invalid=ended();invalid.chronicle.peaks.skill=NaN;assert.throws(()=>R.restore(invalid,G));});
test('中途開始記錄明確標示，復原後不會產生虛假峰值',()=>{let s=G.create('甲','swift','普通');s.year=5;s=R.observe(s,G);const r=R.report(s,G);assert.equal(r.coverage.complete,false);assert.equal(r.coverage.since,19);assert.ok(r.coverage.note.includes('19'));});
module.exports={ended};

test('藏卷容量達上限時不覆蓋既有人生',()=>{const s=ended(),entries=[];for(let i=0;i<R.MAX;i++){const next=structuredClone(s);next.chronicle.id='life-'+i;entries.push(...R.add([],next,G));}const snapshot=JSON.stringify(entries);assert.throws(()=>R.add(entries,s,G),/50/);assert.throws(()=>R.merge(entries,R.pack(R.add([],s,G)),G),/50/);assert.equal(JSON.stringify(entries),snapshot);});
test('報告與紀念卡轉義人物名稱，保留完整原文',()=>{const V=require('../records-view'),s=ended();s.name='<img src=x onerror=alert(1)>';const r=R.report(s,G);for(const html of [V.renderReport(r),V.shareSVG(r)]){assert.ok(!html.includes(s.name));assert.ok(html.includes('&lt;img'));}for(const h of s.history)assert.ok(R.text(r).includes(h.text));});

test('匯入寫到一半遭配額拒絕會還原全部原值',()=>{const items=new Map([['game','old'],['archive','old-rolls']]);let writes=0;const storage={getItem:k=>items.get(k)??null,setItem(k,v){if(++writes===2)throw Error('quota');items.set(k,v);},removeItem:k=>items.delete(k)};assert.throws(()=>R.persist(storage,[['game','new'],['archive','new-rolls']]),/已還原/);assert.deepEqual([...items],[['game','old'],['archive','old-rolls']]);R.persist(storage,[['game','new'],['archive','new-rolls']]);assert.equal(items.get('game'),'new');});
